### ISSUE TITLE
Dev Start errors

### ISSUE THREAD

**Issue by passiweinberger** [Artificial-Engineering/lycheeJS#107]
```
 bootstrap.js: Supported methods are console, Buffer
  BOOTUP (58384)
  sorbet.net.Server: Connected to null:4848
  sorbet.net.Server: Connected to null:8080



  Open your web browser and surf to one of the following hosts:


  http://localhost:8080
  http://192.168.0.100:8080
  http://192.168.99.1:8080
  http://[fdf0:73bd:1e17:7db1:c46d:6d4f:9219:416f]:8080



  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (58388)
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (58387)
  BOOTUP (58390)
  BOOTUP (58389)
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (58391)
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (58392)
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (58393)
  BOOTUP (58395)
  BOOTUP (58394)
  fertilizer: BUILD /lib/lychee
  fertilizer: SUCCESS ("/lib/lychee | html/dist")
  sorbet.mod.Fertilizer: SUCCESS ("/lib/lychee | html/dist")
  fertilizer: BUILD /lib/lychee
  fertilizer: SUCCESS ("/lib/lychee | node/dist")
  fertilizer: BUILD /lib/lychee
  sorbet.mod.Fertilizer: SUCCESS ("/lib/lychee | node/dist")
  fertilizer: SUCCESS ("/lib/lychee | html-nwjs/dist")
  sorbet.mod.Fertilizer: SUCCESS ("/lib/lychee | node-sdl/dist")
  sorbet.mod.Fertilizer: SUCCESS ("/lib/lychee | html-nwjs/dist")
  fertilizer: SUCCESS ("/lib/lychee | html-webview/dist")
  sorbet.mod.Fertilizer: SUCCESS ("/lib/lychee | html-webview/dist")
  fertilizer: SUCCESS ("/lib/sorbet | node-sdl/dist")
  sorbet.mod.Fertilizer: SUCCESS ("/lib/sorbet | node-sdl/dist")
  fertilizer: BUILD /lib/sorbet
  fertilizer: PACKAGE /lib/sorbet/build/node-sdl/main sorbet
  fertilizer: BUILD /lib/sorbet
  fertilizer: PACKAGE /lib/sorbet/build/node/main sorbet
  fertilizer: SUCCESS ("/lib/sorbet | node/dist")
  sorbet.mod.Fertilizer: SUCCESS ("/lib/sorbet | node/dist")
  fertilizer: SUCCESS ("/lib/sorbet | node-sdl/main")
  sorbet.mod.Fertilizer: SUCCESS ("/lib/sorbet | node-sdl/main")
  fertilizer: SUCCESS ("/lib/sorbet | node/main")
  sorbet.mod.Fertilizer: SUCCESS ("/lib/sorbet | node/main")
  sorbet.mod.Server: Launched Server for "over-there" (58500 / null:49156)
  sorbet.mod.Server: Launched Server for "lethalmaze" (58501 / null:49155)
  sorbet.mod.Server: Launched Server for "chat" (58502 / null:49154)
  sorbet.mod.Server: Launched Server for "boilerplate" (58503 / null:49153)
  sorbet.mod.Server: Launched Server for "blitzkrieg" (58504 / null:49152)
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (58478)
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (58479)
  BOOTUP (58488)
  BOOTUP (58483)
  BOOTUP (58480)
  BOOTUP (58486)
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (58484)
  BOOTUP (58482)
  BOOTUP (58481)
  BOOTUP (58487)
  BOOTUP (58493)
  BOOTUP (58485)
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (58490)
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (58489)
  BOOTUP (58491)
  BOOTUP (58492)
  bootstrap.js: Supported methods are console, Buffer
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (58498)
  BOOTUP (58499)
  fertilizer: BUILD /projects/chat
  fertilizer: PACKAGE /projects/chat/build/node/server chat
  fertilizer: BUILD /projects/mode7
/Users/passiweinberger/work/lychee/lycheejs-edge/projects/boilerplate/source/Main.js:10
	var _config = attachments["json"].buffer;
	                                 ^

TypeError: Cannot read property 'buffer' of undefined
    at Function.<anonymous> (/Users/passiweinberger/work/lychee/lycheejs-edge/projects/boilerplate/source/Main.js:10:35)
    at Object.lychee.Environment.lychee.Environment.undefined._export_definition (/Users/passiweinberger/work/lychee/lycheejs-edge/lib/lychee/build/node/core.js:1717:37)
    at Object.lychee.Environment.lychee.Environment.undefined._export_loop (/Users/passiweinberger/work/lychee/lycheejs-edge/lib/lychee/build/node/core.js:1505:25)
    at null._repeat (/Users/passiweinberger/work/lychee/lycheejs-edge/lib/lychee/build/node/core.js:2548:21)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
  sorbet.mod.Fertilizer: FAILURE ("/projects/boilerplate | html-nwjs/main")
/Users/passiweinberger/work/lychee/lycheejs-edge/projects/boilerplate/source/Main.js:10
	var _config = attachments["json"].buffer;
	                                 ^

TypeError: Cannot read property 'buffer' of undefined
    at Function.<anonymous> (/Users/passiweinberger/work/lychee/lycheejs-edge/projects/boilerplate/source/Main.js:10:35)
    at Object.lychee.Environment.lychee.Environment.undefined._export_definition (/Users/passiweinberger/work/lychee/lycheejs-edge/lib/lychee/build/node/core.js:1717:37)
    at Object.lychee.Environment.lychee.Environment.undefined._export_loop (/Users/passiweinberger/work/lychee/lycheejs-edge/lib/lychee/build/node/core.js:1505:25)
    at null._repeat (/Users/passiweinberger/work/lychee/lycheejs-edge/lib/lychee/build/node/core.js:2548:21)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
  fertilizer: BUILD /projects/over-there
  sorbet.mod.Fertilizer: FAILURE ("/projects/boilerplate | html-webview/main")
  fertilizer: PACKAGE /projects/over-there/build/node/server over-there
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/mode7
  fertilizer: BUILD /projects/over-there
  fertilizer: BUILD /projects/boilerplate
  fertilizer: PACKAGE /projects/boilerplate/build/node/server boilerplate
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/chat
  fertilizer: SUCCESS ("/projects/chat | node/server")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/chat | node/server")
  fertilizer: BUILD /projects/chat
/Users/passiweinberger/work/lychee/lycheejs-edge/projects/boilerplate/source/Main.js:10
	var _config = attachments["json"].buffer;
	                                 ^

TypeError: Cannot read property 'buffer' of undefined
    at Function.<anonymous> (/Users/passiweinberger/work/lychee/lycheejs-edge/projects/boilerplate/source/Main.js:10:35)
    at Object.lychee.Environment.lychee.Environment.undefined._export_definition (/Users/passiweinberger/work/lychee/lycheejs-edge/lib/lychee/build/node/core.js:1717:37)
    at Object.lychee.Environment.lychee.Environment.undefined._export_loop (/Users/passiweinberger/work/lychee/lycheejs-edge/lib/lychee/build/node/core.js:1505:25)
    at null._repeat (/Users/passiweinberger/work/lychee/lycheejs-edge/lib/lychee/build/node/core.js:2548:21)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
  sorbet.mod.Fertilizer: FAILURE ("/projects/boilerplate | html/main")
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/pong
  fertilizer: SUCCESS ("/projects/mode7 | html/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/mode7 | html/main")
  fertilizer: BUILD /projects/pong
  fertilizer: SUCCESS ("/projects/over-there | html/main")
  fertilizer: PACKAGE /projects/mode7/build/html-nwjs/main mode7
  fertilizer: CONFIGURE
  sorbet.mod.Fertilizer: SUCCESS ("/projects/over-there | html/main")
  fertilizer: BUILD /projects/over-there
  fertilizer: SUCCESS ("/projects/over-there | node/server")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/over-there | node/server")
  fertilizer: SUCCESS ("/projects/boilerplate | node/server")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/boilerplate | node/server")
  fertilizer: SUCCESS ("/projects/chat | html/main")
  fertilizer: PACKAGE /projects/chat/build/html-nwjs/main chat
  sorbet.mod.Fertilizer: SUCCESS ("/projects/chat | html/main")
  fertilizer: PACKAGE /projects/pong/build/html-nwjs/main pong
  fertilizer: BUILD /projects/tictactoe
  fertilizer: SUCCESS ("/projects/pong | html/main")
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/cultivator/editor
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/tictactoe
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/cultivator/ranger
  fertilizer: PACKAGE /projects/over-there/build/html-nwjs/main over-there
  sorbet.mod.Fertilizer: SUCCESS ("/projects/pong | html/main")
  fertilizer: PACKAGE /projects/cultivator/editor/build/html-nwjs/main editor
  fertilizer: PACKAGE /projects/cultivator/ranger/build/html-nwjs/main ranger
  fertilizer: SUCCESS ("/projects/tictactoe | html/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/tictactoe | html/main")
  fertilizer: PACKAGE /projects/tictactoe/build/html-nwjs/main tictactoe
  fertilizer: SUCCESS ("/projects/over-there | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/over-there | html-nwjs/main")
  fertilizer: SUCCESS ("/projects/cultivator/editor | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/cultivator/editor | html-nwjs/main")
  fertilizer: SUCCESS ("/projects/chat | html-nwjs/main")
  fertilizer: SUCCESS ("/projects/tictactoe | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/chat | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/tictactoe | html-nwjs/main")
  fertilizer: SUCCESS ("/projects/mode7 | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/mode7 | html-nwjs/main")
  fertilizer: SUCCESS ("/projects/pong | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/pong | html-nwjs/main")
  fertilizer: SUCCESS ("/projects/cultivator/ranger | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/cultivator/ranger | html-nwjs/main")

```

**Comment by cookiengineer** [comment]
```
/Users/passiweinberger/work/lychee/lycheejs-edge/projects/boilerplate/source/Main.js:10
    var _config = attachments["json"].buffer;
                                     ^

TypeError: Cannot read property 'buffer' of undefined
```

This means that the boilerplate is currently broken and throws a javascript error. The related issue for discussion of how those logs are treated is in issue [#106](https://github.com/Artificial-Engineering/lycheeJS/issues/106).

Everything else works fine and as expected. sorbet is able to build itself, lychee, the fertilizer and all other projects and cross-compiles them to all given platforms successfully.

**Comment by passiweinberger** [comment]
```
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (91800)
  BOOTUP (91794)
  BOOTUP (91799)
  BOOTUP (91797)
  BOOTUP (91802)
  bootstrap.js: Supported methods are console, Buffer
  BOOTUP (91804)
  BOOTUP (91805)
  BOOTUP (91801)
  BOOTUP (91803)
  fertilizer: BUILD /projects/boilerplate
  fertilizer: PACKAGE /projects/boilerplate/build/node/server boilerplate
/Users/passiweinberger/work/lychee/projects/boilerplate/source/Main.js:10
	var _config = attachments["json"].buffer;
	                                 ^

TypeError: Cannot read property 'buffer' of undefined
    at Function.<anonymous> (/Users/passiweinberger/work/lychee/projects/boilerplate/source/Main.js:10:35)
    at Object.lychee.Environment.lychee.Environment.undefined._export_definition (/Users/passiweinberger/work/lychee/lib/lychee/build/node/core.js:1717:37)
    at Object.lychee.Environment.lychee.Environment.undefined._export_loop (/Users/passiweinberger/work/lychee/lib/lychee/build/node/core.js:1505:25)
    at null._repeat (/Users/passiweinberger/work/lychee/lib/lychee/build/node/core.js:2548:21)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
  sorbet.mod.Fertilizer: FAILURE ("/projects/boilerplate | html-nwjs/main")
/Users/passiweinberger/work/lychee/projects/boilerplate/source/Main.js:10
	var _config = attachments["json"].buffer;
	                                 ^

TypeError: Cannot read property 'buffer' of undefined
    at Function.<anonymous> (/Users/passiweinberger/work/lychee/projects/boilerplate/source/Main.js:10:35)
    at Object.lychee.Environment.lychee.Environment.undefined._export_definition (/Users/passiweinberger/work/lychee/lib/lychee/build/node/core.js:1717:37)
    at Object.lychee.Environment.lychee.Environment.undefined._export_loop (/Users/passiweinberger/work/lychee/lib/lychee/build/node/core.js:1505:25)
    at null._repeat (/Users/passiweinberger/work/lychee/lib/lychee/build/node/core.js:2548:21)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
  fertilizer: SUCCESS ("/projects/boilerplate | node/server")
  sorbet.mod.Fertilizer: FAILURE ("/projects/boilerplate | html-webview/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/boilerplate | node/server")
/Users/passiweinberger/work/lychee/projects/boilerplate/source/Main.js:10
	var _config = attachments["json"].buffer;
	                                 ^

TypeError: Cannot read property 'buffer' of undefined
    at Function.<anonymous> (/Users/passiweinberger/work/lychee/projects/boilerplate/source/Main.js:10:35)
    at Object.lychee.Environment.lychee.Environment.undefined._export_definition (/Users/passiweinberger/work/lychee/lib/lychee/build/node/core.js:1717:37)
    at Object.lychee.Environment.lychee.Environment.undefined._export_loop (/Users/passiweinberger/work/lychee/lib/lychee/build/node/core.js:1505:25)
    at null._repeat (/Users/passiweinberger/work/lychee/lib/lychee/build/node/core.js:2548:21)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
  sorbet.mod.Fertilizer: FAILURE ("/projects/boilerplate | html/main")
  fertilizer: BUILD /projects/chat
  fertilizer: BUILD /projects/over-there
  fertilizer: PACKAGE /projects/chat/build/node/server chat
  fertilizer: PACKAGE /projects/over-there/build/node/server over-there
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/chat
  fertilizer: BUILD /projects/mode7
  fertilizer: SUCCESS ("/projects/mode7 | html/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/mode7 | html/main")
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/mode7
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/cultivator/ranger
  fertilizer: SUCCESS ("/projects/chat | node/server")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/chat | node/server")
  fertilizer: SUCCESS ("/projects/over-there | node/server")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/over-there | node/server")
  fertilizer: PACKAGE /projects/chat/build/html-nwjs/main chat
  fertilizer: BUILD /projects/chat
  fertilizer: PACKAGE /projects/mode7/build/html-nwjs/main mode7
  fertilizer: BUILD /projects/over-there
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/pong
  fertilizer: BUILD /projects/cultivator/editor
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/pong
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/tictactoe
  fertilizer: PACKAGE /projects/cultivator/ranger/build/html-nwjs/main ranger
  fertilizer: BUILD /projects/tictactoe
  fertilizer: CONFIGURE
  fertilizer: BUILD /projects/over-there
  fertilizer: SUCCESS ("/projects/pong | html/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/pong | html/main")
  fertilizer: PACKAGE /projects/cultivator/editor/build/html-nwjs/main editor
  fertilizer: PACKAGE /projects/pong/build/html-nwjs/main pong
  fertilizer: SUCCESS ("/projects/over-there | html/main")
  fertilizer: SUCCESS ("/projects/chat | html/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/chat | html/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/over-there | html/main")
  fertilizer: PACKAGE /projects/over-there/build/html-nwjs/main over-there
  fertilizer: SUCCESS ("/projects/tictactoe | html/main")
  fertilizer: PACKAGE /projects/tictactoe/build/html-nwjs/main tictactoe
  sorbet.mod.Fertilizer: SUCCESS ("/projects/tictactoe | html/main")
  fertilizer: SUCCESS ("/projects/mode7 | html-nwjs/main")
  fertilizer: SUCCESS ("/projects/cultivator/ranger | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/mode7 | html-nwjs/main")
  fertilizer: SUCCESS ("/projects/chat | html-nwjs/main")
  fertilizer: SUCCESS ("/projects/tictactoe | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/cultivator/ranger | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/chat | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/tictactoe | html-nwjs/main")
  fertilizer: SUCCESS ("/projects/pong | html-nwjs/main")
  fertilizer: SUCCESS ("/projects/over-there | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/over-there | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/pong | html-nwjs/main")
  fertilizer: SUCCESS ("/projects/cultivator/editor | html-nwjs/main")
  sorbet.mod.Fertilizer: SUCCESS ("/projects/cultivator/editor | html-nwjs/main")

```

**Comment by passiweinberger** [comment]
still there :)

**Comment by CodeKittey** [comment]
can you visit localhost:8080. If yes its fixed if not its the same like Issue106

**Comment by cookiengineer** [comment]
This is fixed by now, on both OSX and Linux. If it doesn't work again, please reopen this issue.
